name: Actualizar Perfil

on:
  schedule:
    - cron: "0 */12 * * *" # Se ejecuta cada 12 horas
  workflow_dispatch: # Permite ejecutarlo manualmente
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile ReadMe
    
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - uses: Readme-Workflows/recent-activity@v2.4.1 # Ejemplo de acción del Marketplace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
